apiVersion: v1
data:
  CUSTOMER_SERVICE_URI: http://customer-service
kind: ConfigMap
metadata:
  name: customer-consumer-env
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: default
spec:
  containers:
  - name: mmv3-kafka-consumer
    image: mjuharia76/mmv3-kafka-consumer:0.0.3-SNAPSHOT
#    resources:
#      requests:
#        memory: "4Gi"
#        cpu: "4G"
#      limits:
#        memory: "8Gi"
#        cpu: "8G"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - image: mjuharia76/mmv3-kafka-consumer:0.0.3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-kafka-consumer
        envFrom:
          - configMapRef:
              name: customer-consumer-env
        #env:
        #  - name: CUSTOMER_SERVICE_URI
        #    value: http://customer-service
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
     
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
  namespace: default 
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: kafka-consumer
  sessionAffinity: None
  type: LoadBalancer
  




