apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: default
spec:
  containers:
  - name: mmv3-kafka-producer
    image: mjuharia76/mmv3-kafka-producer:0.0.1-SNAPSHOT
#    resources:
#      requests:
#        memory: "4Gi"
#        cpu: "4G"
#      limits:
#        memory: "8Gi"
#        cpu: "8G"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - image: mjuharia76/mmv3-kafka-producer:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-kafka-producer
        readinessProbe:
          httpGet:
            port: 9100
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 9100
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
     
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: default
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: kafka-producer
  sessionAffinity: None
  type: LoadBalancer
  



