apiVersion: v1
kind: Pod
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: default
spec:
  containers:
  - name: mmv3-customer-service
    image: mjuharia76/mmv3-customer-service:0.0.4-SNAPSHOT
#    resources:
#      requests:
#        memory: "4Gi"
#        cpu: "4G"
#      limits:
#        memory: "8Gi"
#        cpu: "8G"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: customer-service
  name: customer-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - image: mjuharia76/mmv3-customer-service:0.0.4-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-customer-service
        readinessProbe:
          httpGet:
            port: 7100
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 7100
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
     
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: default 
spec:
  ports:
  - port: 7100
    protocol: TCP
    targetPort: 7100
  selector:
    app: customer-service
  sessionAffinity: None
  type: LoadBalancer
  



