apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: moso-dev
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-reverse-proxy
        image: nginx-reverse-proxy

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: moso-dev
  annotations:
    kubernetes.io/aws-load-balancer-type: external
    kubernetes.io/aws-load-balancer-scheme: internet-facing
    kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
